# Generated by Django 4.1.10 on 2023-09-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('IdCat', models.AutoField(primary_key=True, serialize=False)),
                ('CatName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('IdUser', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=20)),
                ('Passwd', models.CharField(max_length=12)),
                ('UserMail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('IdDepense', models.AutoField(primary_key=True, serialize=False)),
                ('Montant', models.FloatField(max_length=15)),
                ('DateDep', models.DateField(max_length=9)),
                ('Description', models.CharField(max_length=20)),
                ('IdCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackApp.categorie')),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackApp.user')),
            ],
        ),
    ]
